config/routes.rb
Webfoo::Application.routes.draw do
  get "aboutus/index"

  

end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
  	@gitusers = [{"login" =>  "helios", "name" =>"Raoul Jean Pierre Bonnal", "avatar_url" =>"helios.jpeg"},
  	             {"login" => "ktym", "name" =>"Toshiaki Katayama", "avatar_url" =>"ktym.jpg"},
  	             {"login" => "joejimbo", "name" =>"Joachim Baran", "avatar_url" =>"joejimbo.jpeg"},
  	             {"login" => "erikiv", "name" =>"Eri Kibukawa", "avatar_url" =>"octocat.png"},
  	             {"login" => "fstrozzi", "name" =>"Francesco Strozzi", "avatar_url" => "fstrozzi.jpeg"},
  	             {"login" => "pjotrp", "name"  =>"Pjotr Prins", "avatar_url" =>"pjotrp.jpeg"}]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aboutus/index.html.erb
      <div class="container">
  <div class="row">

    <div class="span7">
<p>Ruby/Biogem developers can create your own app
- You can easily utilize your NGS biogem w/ BaseSpace Ruby SDK
- You will easily obtain much more users

Users can use your app without coding
- Don't need to learn programming. Just a click!

BioBaseSpace for non-Ruby programmers

Then we found that it can be a burden to create new Web app from scratch on top of your NGS program. So we started new project to provide a Web-app scaffold for BS. We have already implemented the basic portion but will need some more time before releasing the app (BioBaseSpace).
</p>

      <p>Bio::BaseSpace is a Ruby based SDK to be used in the development of Apps and scripts for working with Illumina's BaseSpace cloud-computing solution for next-gen sequencing data analysis.

The primary purpose of the SDK is to provide an easy-to-use Ruby environment enabling developers to authenticate a user, retrieve data, and upload data/results from their own analysis to BaseSpace.

Note: It will be necessary to have created a BaseSpace account with a new App and have the client_key and client_secret codes for the App available to run a number of the following examples.</p>        


    </div>
    <div class="span5">
<table class="table table-striped table-condensed" >
<tr>
<th></th>
<th>Name</th>
</tr>
<% @gitusers.each do |user| %>
<tr>
<td><%= image_tag user['avatar_url'], size: "80x80" %></td>
<td><%= user["name"] || user["login"] %></td>
</tr>
<% end %> 
</table>
    </div>    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basespace Ruby Dojo</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">BaseSpace Browsing</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Samples", samples_path %></li>
          <li><%= link_to "Contact Us" %></li>
          <li><%= link_to "About", aboutus_index_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>
</body>
</html>